name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install pylint
        # astroid 2.2.0 seems to break everything in Pylint
        pip install astroid==2.1.0
        # isort above 4.3.4 introduces the "__init__.py not found" issue
        pip install isort==4.3.4
    - name: Run black
      run: |
        black --check --verbose .
    - name: Run pylint
      run: |
        pylint .